### ISSUE TITLE
where use ValidationInterface?

### ISSUE THREAD

**Issue by alirezarahmani** [bencagri/symfony4-ddd#2]
I was wondering if you implement ValidationInterface classes where you use them ? in service layer? in controller?

**Comment by alirezarahmani** [comment]
@bencagri

**Comment by bencagri** [comment]
hi @alirezarahmani Controllers should be standalone classes. Validation should be under *domain*, so injecting **validators** in services would be good choice.

**Comment by alirezarahmani** [comment]
@bencagri If you wonder you may answer here: https://stackoverflow.com/questions/52761074/where-should-put-input-validation-in-domain-driven-design too. thanks
